#!/bin/bash
cat << EOF
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM]  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM]  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM\  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMM            MM#  (#^     .HM"      ?MMM#  (MMMMMMMF  JMN,  UMMMMM^ .dMMMM
MMMMMMMM]  MMMMMMMM#   .JMMMN    .MMMM,  dMM#  (MMMMMMMF  JMMMe  ?MM@  .MMMMMM
MMMMMMMM]  MMMMMMMM#  -MMMMMM)  MMMMMM#  .MM#  (MMMMMMMF  JMMMMk  ,"  .MMMMMMM
MMMMMMMM]  MMMMMMMM#  (MMMMMM)  MMMMMM#  .MM#  (MMMMMMMF  JMMMMMN,  .MMMMMMMMM
MMMMMMMM]  MMMMMMMM#  (MMMMMM)  MMMMMM#  .MM#  (MMMMMMMF  JMMMMMD    7MMMMMMMM
MMMMMMMM]  MMMMMMMM#  (MMMMMM)  MMMMMM#  .MM#  -MMMMMMMt  JMMMMt .db  ,MMMMMMM
MMMMMMMMb  .YMMH"MM#  (MMMMMM)  MMMMMM#  .MMM,  ?WMM9^ .  JMM#! .MMMN. .HMMMMM
MMMMMMMMMN,.     MM#  (MMMMMM)  MMMMMM#  .MMMMa.    ..MF  JMF  .MMMMMM,  TMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
EOF
